- name: install and run
  Hosts: web
  become: yes  # -b means first become root
  tasks:
  - name: install nginx
    ansible.builtin.packages:
     name: nginx
     status: present
  - name: start the nginx
    ansible.builtin.service:
      name: nginx
      state: started