- name: install and run
  hosts: web
  become: yes # -b 
  tasks:
  - name: install nginx
    ansible.builtin.package:
     name: nginx
     status: present
  - name: start the nginx
    ansible.builtin.service:
      name: nginx
      state: started