- name: variables
  hosts: local
  connection: local
  vars:                        # play level variables, global variables
    COURSE: "Devops with AWS"
    DURATION: 120HRS
    TRAINER: SIVAKUMAR
  tasks:
  - name: print the variables
    vars:
      COURSE: Ansible
    ansible.buitin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ Duration }}, Trainer is {{ TRAINER }}"
