- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefine variable
    ansible.builtin.debug:
     msg: "Hello {{ person | default ('suneetha')}}"

  - name: convert string to list
    vars:
      fruits: "apple, banana, orange"     #string 
    ansible.builtin.debug:
     msg: "Fruits are:  {{ fruits | split('.')}}"


  - name: convert map into list
    vars:
      course:
         name: ansible
         Duration: 10hrs
         Trainer: siva 
    ansible.builtin.debug:
     msg: "Course info:  {{ course | dict2items }}"

  - name: convert upper case to lower
    vars:
      Name: "SivA KuMaR ReDdy"     
    ansible.builtin.debug:
     msg: "Hello {{ Name | lower}}"

  - name: convert lower case to upper
    vars:
      Name: "SivA KuMaR ReDdy"     
    ansible.builtin.debug:
     msg: "Hello {{ Name | upper }}"
  
  - name: print max to min numbers
    vars:
      Numbers: [10,120, 1,2,3,451235]     
    ansible.builtin.debug:
     msg: "Min is: {{ Numbers | min }} Max is:  {{ Numbers | max }} "

  - name: Check ip address is valid or not 
    vars:
      ip: "650.255.7050.230"
    ansible.builtin.debug:
     msg: "{ { ip | ansible.utils.ipaddr} }"





  