- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefine variable
    ansible.builtin.debug:
     msg: "Hello {{ person | default ('suneetha')}}"

  - name: convert string to list
    vars:
      fruits: "apple, banana, orange"     #string 
    ansible.builtin.debug:
     msg: "Fruits are:  {{ fruits | split('.')}}"



  